// ****************************************************************************
// <author>Stephen Cleary</author>
// <date>04-2014</date>
// <web>https://msdn.microsoft.com/en-us//magazine/dn630647.aspx</web>
// ****************************************************************************
// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>

using System.Threading.Tasks;
using System.Windows.Input;
using Sharpnado.Tasks;

namespace SillyCompany.Mobile.Practices.Presentation.Commands
{

    public interface IAsyncCommand : ICommand
    {
        ITaskMonitor Execution { get; }

        Task ExecuteAsync(object parameter);

        void RaiseCanExecuteChanged();
    }

    public interface IAsyncCommand<TResult> : ICommand
    {
        TaskMonitor<TResult> Execution { get; }
    }
}