//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SillyCompany.Mobile.Practices.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Filmos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Filmos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SillyCompany.Mobile.Practices.Localization.Filmos", typeof(Filmos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### 2018
        ///##### Vice 
        ///Donald Rumsfeld
        ///
        ///#### 2015
        ///##### The Big Short
        ///Mark Baum
        ///
        ///#### 2014
        ///##### Foxcatcher 
        ///John du Pont
        ///
        ///#### The Office (2005-2013)
        ///##### BoJack Horseman (TV Series) 
        ///Michael Scott
        ///
        ///#### 2005
        ///##### The 40 Year Old Virgin
        ///Andy
        ///
        ///#### 2004
        ///##### Anchorman: The Legend of Ron Burgundy
        ///Anchorman: The Legend of Ron Burgundy
        ///
        ///#### 2003
        ///##### Bruce Almighty
        ///Evan Baxter.
        /// </summary>
        internal static string Carell {
            get {
                return ResourceManager.GetString("Carell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### 2017
        ///##### Daddy&apos;s Home Two 
        ///Brad
        ///
        ///#### 2015
        ///##### Very Bad Dads 
        ///Brad Whitaker
        ///
        ///##### Get Hard 
        ///James
        ///
        ///#### 2013
        ///##### Anchorman 2: The Legend Continues
        ///Ron Burgundy
        ///
        ///#### 2010
        ///##### Very Bad Cops 
        ///Allen Gamble
        ///
        ///
        ///#### 2009
        ///##### Land of the Lost
        ///Dr. Rick Marshall
        ///
        ///
        ///#### 2008
        ///##### Semi-Pro 
        ///#### 2017
        ///##### Daddy&apos;s Home Two 
        ///Brad
        ///
        ///#### 2015
        ///##### Very Bad Dads 
        ///Brad Whitaker
        ///
        ///##### Get Hard 
        ///James
        ///
        ///#### 2013
        ///##### Anchorman 2: The Legend Continues
        ///Ron Burgundy
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ferrell {
            get {
                return ResourceManager.GetString("Ferrell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### 2015
        ///##### BoJack Horseman (TV Series) 
        ///Hedgehog at Orphanage
        ///
        ///#### 2009
        ///##### The Invention of Lying 
        ///Mark Bellison
        ///
        ///#### 2006
        ///##### Night at the Museum 
        ///Dr. McPhee
        ///
        ///#### 2001-2003
        ///##### The Office
        ///David Brent.
        /// </summary>
        internal static string Gervais {
            get {
                return ResourceManager.GetString("Gervais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### 1994
        ///##### La cité de la peur
        ///Les Nuls
        ///
        ///#### 1990
        ///##### Les nuls, l&apos;émission
        ///Les Nuls.
        /// </summary>
        internal static string LesNuls {
            get {
                return ResourceManager.GetString("LesNuls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### 2019
        ///##### The Souvenir 
        ///Patrick
        ///
        ///#### 2017
        ///##### Paddington 2 
        ///Forensic Investigator
        ///
        ///#### 2006-2013
        ///##### The IT Crowd (TV Movie) 
        ///Maurice Moss.
        /// </summary>
        internal static string Moss {
            get {
                return ResourceManager.GetString("Moss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### 1998
        ///##### The First Snow of Winter (Short) 
        ///Voley (voice)
        ///
        ///#### 1995-1998
        ///##### Father Ted (TV Series) 
        ///Father Ted Crilly
        ///
        ///#### 1988
        ///##### Taffin 
        ///Micky Guest.
        /// </summary>
        internal static string Ted {
            get {
                return ResourceManager.GetString("Ted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### 2004
        ///##### Late Night with Conan O&apos;Brien
        ///Triumph The Insult Comic Dog.
        /// </summary>
        internal static string Triumph {
            get {
                return ResourceManager.GetString("Triumph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### 1996
        ///##### Friends (TV Series) 
        ///Jean-Claude Van Damme
        ///
        ///#### 1993
        ///##### Last Action Hero 
        ///Jean-Claude Van Damme
        ///
        ///#### 1992
        ///##### Universal Soldier 
        ///Luc Deveraux / GR44
        ///
        ///#### 1991
        ///##### Double Impact 
        ///Alex / Chad Wagner
        ///
        ///#### 1990
        ///##### Full Contact 
        ///Lyon
        ///
        ///#### 1989
        ///##### Kickboxer 
        ///Kurt Sloane
        ///
        ///#### 1988
        ///##### Bloodsport
        ///Frank Dux.
        /// </summary>
        internal static string VanDamme {
            get {
                return ResourceManager.GetString("VanDamme", resourceCulture);
            }
        }
    }
}
