//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SillyCompany.Mobile.Practices.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Filmos {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Filmos() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SillyCompany.Mobile.Practices.Localization.Filmos", typeof(Filmos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Carell {
            get {
                return ResourceManager.GetString("Carell", resourceCulture);
            }
        }
        
        internal static string Ferrell {
            get {
                return ResourceManager.GetString("Ferrell", resourceCulture);
            }
        }
        
        internal static string Gervais {
            get {
                return ResourceManager.GetString("Gervais", resourceCulture);
            }
        }
        
        internal static string LesNuls {
            get {
                return ResourceManager.GetString("LesNuls", resourceCulture);
            }
        }
        
        internal static string Moss {
            get {
                return ResourceManager.GetString("Moss", resourceCulture);
            }
        }
        
        internal static string Ted {
            get {
                return ResourceManager.GetString("Ted", resourceCulture);
            }
        }
        
        internal static string Triumph {
            get {
                return ResourceManager.GetString("Triumph", resourceCulture);
            }
        }
        
        internal static string VanDamme {
            get {
                return ResourceManager.GetString("VanDamme", resourceCulture);
            }
        }
    }
}
